backend:
  name: github
  repo: bilafish/portfolio-site
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "Upload asset “{{path}}”"
    deleteMedia: "Delete asset “{{path}}”"

media_folder: static/assets
public_folder: /assets

collections:
  - name: project
    label: Project
    folder: "src/pages/works"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "project-page",
        }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { label: "Project Thumbnail", name: "projectthumbnail", widget: image }
      - {
          label: "Project Thumbnail Background Colour",
          name: "thumbnailbgcolour",
          widget: string,
        }
      - {
          label: "Website URL",
          name: "weburl",
          widget: string,
          required: false,
        }
      - {
          label: "Github Repo",
          name: "githubrepo",
          widget: string,
          required: false,
        }
      - {
          label: "Screenshots Gallery",
          name: "screenshots",
          widget: "list",
          field: { label: Screenshot, name: screen, widget: image },
          required: false,
        }
      - { name: body, label: Body, widget: markdown, required: false }
      - { label: "Tags", name: "tags", widget: "list" }
